color0 #171212
color1 #ffb4ab
color2 #fab5b4
color3 #e2bebd
color4 #e9c085
color5 #fab5b4
color6 #e2bebd
color7 #ebe0df
color8 #9f8d8c
color9 #ffb4ab
color10 #fab5b4
color11 #e2bebd
color12 #e9c085
color13 #fab5b4
color14 #e2bebd
color15 #ebe0df

cursor                #ebe0df
cursor_text_color     #171212
background            #171212
foreground            #ebe0df
selection_foreground  #d6c2c1
selection_background  #524343
active_border_color   #fab5b4
inactive_border_color #524343
url_color             #fab5b4

active_tab_foreground   #4f2324
active_tab_background   #fab5b4
inactive_tab_foreground #d6c2c1
inactive_tab_background #524343
cursor_trail_color      #d6c2c1
